/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dda;

import java.awt.Graphics;

/**
 *
 * @author abdalrahman
 */
public class DDAF extends javax.swing.JFrame {
double x1 , y1 ,x2 ,y2 ,m ,step , dx , dy ,y, x, increx , increy  ; 
    /**
     * Creates new form DDAF
     */
    public DDAF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        x1tf = new javax.swing.JTextField();
        y1tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        y2tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        x2tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(199, 202, 202));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        runbutton.setBackground(new java.awt.Color(255, 255, 255));
        runbutton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        runbutton.setText("Run");
        runbutton.setBorder(null);
        runbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(runbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 95, 74, 24));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("x1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 21, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 144, 1, -1));

        x1tf.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        x1tf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        jPanel1.add(x1tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 20, 70, -1));

        y1tf.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        y1tf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        jPanel1.add(y1tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 64, 70, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("y1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 65, -1, -1));

        y2tf.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        y2tf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        jPanel1.add(y2tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 64, 70, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("y2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 65, -1, -1));

        x2tf.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        x2tf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        jPanel1.add(x2tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 20, 70, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("x2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 21, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 144, 510, 154));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runbuttonActionPerformed

//        form2 f=new form2();
//        f.setVisible(true);
        
        x1 = Double.parseDouble(x1tf.getText()) ; 
y1 = Double.parseDouble(y1tf.getText()) ; 
x2 = Double.parseDouble(x2tf.getText()) ; 
y2 = Double.parseDouble(y2tf.getText()) ; 

dx = x2 -x1 ; 
dy = y2 -y1 ; 
m = dy/dx ; 
if(Math.abs(dx)>=Math.abs(dy)){
step = Math.abs(dx) ; 

}
else {
step = Math.abs(dy);
}
increx = dx /step ; 
increy = dy /step ; 
x = x1 ; 
y = y1 ; 
Graphics g = jPanel2.getGraphics(); 

for(int i = 0 ; i<step ; i++){
   
    g.fillOval((int)x,(int)y,2,2);
    

x = x + increx ;
y = y + increy ;


}    
    }//GEN-LAST:event_runbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DDAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DDAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DDAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DDAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DDAF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton runbutton;
    private javax.swing.JTextField x1tf;
    private javax.swing.JTextField x2tf;
    private javax.swing.JTextField y1tf;
    private javax.swing.JTextField y2tf;
    // End of variables declaration//GEN-END:variables
}
